name: Build and Test Java Code
on:
  push:
    main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Java code
      run: mvn clean install -DskipTests=true
    - name: Test
      run: echo 'Success: Build and test completed successfully!'